[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
vn_core = { path = "../vn_core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
postcard = { version = "1.1.3", features = ["use-std"] }
raylib = "5.5.1"
